
package gov.usda.nrcs.wcc.awdbWebService;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AwdbWebService", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AwdbWebService {


    /**
     * 
     * @param forecastPeriod
     * @param elementCd
     * @param stationTriplet
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.Forecast>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecasts", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecasts")
    @ResponseWrapper(localName = "getForecastsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastsResponse")
    public List<Forecast> getForecasts(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "forecastPeriod", targetNamespace = "")
        String forecastPeriod);

    /**
     * 
     * @param beginPublicationDate
     * @param forecastPeriod
     * @param elementCd
     * @param stationTriplet
     * @param endPublicationDate
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.Forecast>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastsByPubDate", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastsByPubDate")
    @ResponseWrapper(localName = "getForecastsByPubDateResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastsByPubDateResponse")
    public List<Forecast> getForecastsByPubDate(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "forecastPeriod", targetNamespace = "")
        String forecastPeriod,
        @WebParam(name = "beginPublicationDate", targetNamespace = "")
        String beginPublicationDate,
        @WebParam(name = "endPublicationDate", targetNamespace = "")
        String endPublicationDate);

    /**
     * 
     * @param stationIds
     * @param minElevation
     * @param elementCds
     * @param countyNames
     * @param logicalAnd
     * @param ordinals
     * @param hucs
     * @param stateCds
     * @param maxLongitude
     * @param minLatitude
     * @param networkCds
     * @param minLongitude
     * @param maxLatitude
     * @param maxElevation
     * @param heightDepths
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStations", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStations")
    @ResponseWrapper(localName = "getStationsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationsResponse")
    public List<String> getStations(
        @WebParam(name = "stationIds", targetNamespace = "")
        List<String> stationIds,
        @WebParam(name = "stateCds", targetNamespace = "")
        List<String> stateCds,
        @WebParam(name = "networkCds", targetNamespace = "")
        List<String> networkCds,
        @WebParam(name = "hucs", targetNamespace = "")
        List<String> hucs,
        @WebParam(name = "countyNames", targetNamespace = "")
        List<String> countyNames,
        @WebParam(name = "minLatitude", targetNamespace = "")
        BigDecimal minLatitude,
        @WebParam(name = "maxLatitude", targetNamespace = "")
        BigDecimal maxLatitude,
        @WebParam(name = "minLongitude", targetNamespace = "")
        BigDecimal minLongitude,
        @WebParam(name = "maxLongitude", targetNamespace = "")
        BigDecimal maxLongitude,
        @WebParam(name = "minElevation", targetNamespace = "")
        BigDecimal minElevation,
        @WebParam(name = "maxElevation", targetNamespace = "")
        BigDecimal maxElevation,
        @WebParam(name = "elementCds", targetNamespace = "")
        List<String> elementCds,
        @WebParam(name = "ordinals", targetNamespace = "")
        List<Integer> ordinals,
        @WebParam(name = "heightDepths", targetNamespace = "")
        List<HeightDepth> heightDepths,
        @WebParam(name = "logicalAnd", targetNamespace = "")
        boolean logicalAnd);

    /**
     * 
     * @param duration
     * @param stationTriplets
     * @param beginDay
     * @param endDay
     * @param heightDepth
     * @param elementCd
     * @param getFlags
     * @param endMonth
     * @param beginMonth
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.AveragesData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAveragesData", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetAveragesData")
    @ResponseWrapper(localName = "getAveragesDataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetAveragesDataResponse")
    public List<AveragesData> getAveragesData(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "duration", targetNamespace = "")
        Duration duration,
        @WebParam(name = "getFlags", targetNamespace = "")
        boolean getFlags,
        @WebParam(name = "beginMonth", targetNamespace = "")
        int beginMonth,
        @WebParam(name = "beginDay", targetNamespace = "")
        int beginDay,
        @WebParam(name = "endMonth", targetNamespace = "")
        int endMonth,
        @WebParam(name = "endDay", targetNamespace = "")
        int endDay);

    /**
     * 
     * @param beginDate
     * @param endHour
     * @param stationTriplets
     * @param endDate
     * @param beginHour
     * @param heightDepth
     * @param elementCd
     * @param ordinal
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.HourlyData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHourlyData", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetHourlyData")
    @ResponseWrapper(localName = "getHourlyDataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetHourlyDataResponse")
    public List<HourlyData> getHourlyData(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "ordinal", targetNamespace = "")
        int ordinal,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "beginDate", targetNamespace = "")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate,
        @WebParam(name = "beginHour", targetNamespace = "")
        Integer beginHour,
        @WebParam(name = "endHour", targetNamespace = "")
        Integer endHour);

    /**
     * 
     * @return
     *     returns gov.usda.nrcs.wcc.awdbWebService.Diagnostics
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runDiagnostics", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.RunDiagnostics")
    @ResponseWrapper(localName = "runDiagnosticsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.RunDiagnosticsResponse")
    public Diagnostics runDiagnostics();

    /**
     * 
     * @param stationTriplet
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.ForecastEquation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastEquations", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastEquations")
    @ResponseWrapper(localName = "getForecastEquationsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastEquationsResponse")
    public List<ForecastEquation> getForecastEquations(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet);

    /**
     * 
     * @param unitCd
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUnitName", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetUnitName")
    @ResponseWrapper(localName = "getUnitNameResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetUnitNameResponse")
    public String getUnitName(
        @WebParam(name = "unitCd", targetNamespace = "")
        String unitCd);

    /**
     * 
     * @param stationTriplets
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.StationMetaData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStationMetadataMultiple", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationMetadataMultiple")
    @ResponseWrapper(localName = "getStationMetadataMultipleResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationMetadataMultipleResponse")
    public List<StationMetaData> getStationMetadataMultiple(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets);

    /**
     * 
     * @param stationTriplet
     * @return
     *     returns gov.usda.nrcs.wcc.awdbWebService.ForecastPoint
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastPoint", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPoint")
    @ResponseWrapper(localName = "getForecastPointResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPointResponse")
    public ForecastPoint getForecastPoint(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet);

    /**
     * 
     * @param durationCd
     * @param endWaterYear
     * @param stationTriplets
     * @param beginWaterYear
     * @param heightDepth
     * @param elementCd
     * @param ordinal
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.StationDataAssuredFlags>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStationDataAssuredFlags", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationDataAssuredFlags")
    @ResponseWrapper(localName = "getStationDataAssuredFlagsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationDataAssuredFlagsResponse")
    public List<StationDataAssuredFlags> getStationDataAssuredFlags(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "ordinal", targetNamespace = "")
        int ordinal,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "durationCd", targetNamespace = "")
        String durationCd,
        @WebParam(name = "beginWaterYear", targetNamespace = "")
        int beginWaterYear,
        @WebParam(name = "endWaterYear", targetNamespace = "")
        int endWaterYear);

    /**
     * 
     * @param stationTriplets
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.ForecastEquation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastEquationsMultiple", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastEquationsMultiple")
    @ResponseWrapper(localName = "getForecastEquationsMultipleResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastEquationsMultipleResponse")
    public List<ForecastEquation> getForecastEquationsMultiple(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets);

    /**
     * 
     * @param centralTendencyType
     * @param stationTriplets
     * @param periods
     * @param elementCd
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.ForecastPeriodCentralTendency>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastPeriodCentralTendency", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPeriodCentralTendency")
    @ResponseWrapper(localName = "getForecastPeriodCentralTendencyResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPeriodCentralTendencyResponse")
    public List<ForecastPeriodCentralTendency> getForecastPeriodCentralTendency(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "periods", targetNamespace = "")
        List<String> periods,
        @WebParam(name = "centralTendencyType", targetNamespace = "")
        CentralTendencyType centralTendencyType);

    /**
     * 
     * @param elementCd
     * @return
     *     returns gov.usda.nrcs.wcc.awdbWebService.Element
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getElement", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetElement")
    @ResponseWrapper(localName = "getElementResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetElementResponse")
    public Element getElement(
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd);

    /**
     * 
     * @param publicationMonth
     * @param probability
     * @param forecastPeriod
     * @param publicationYear
     * @param elementCd
     * @param stationTriplet
     * @param publicationDay
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastValue", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastValue")
    @ResponseWrapper(localName = "getForecastValueResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastValueResponse")
    public BigDecimal getForecastValue(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "forecastPeriod", targetNamespace = "")
        String forecastPeriod,
        @WebParam(name = "probability", targetNamespace = "")
        int probability,
        @WebParam(name = "publicationYear", targetNamespace = "")
        int publicationYear,
        @WebParam(name = "publicationMonth", targetNamespace = "")
        int publicationMonth,
        @WebParam(name = "publicationDay", targetNamespace = "")
        int publicationDay);

    /**
     * 
     * @param forecaster
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.Configuration>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastConfigurations", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastConfigurations")
    @ResponseWrapper(localName = "getForecastConfigurationsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastConfigurationsResponse")
    public List<Configuration> getForecastConfigurations(
        @WebParam(name = "forecaster", targetNamespace = "")
        String forecaster);

    /**
     * 
     * @param duration
     * @param centralTendencyType
     * @param stationTriplets
     * @param heightDepth
     * @param elementCd
     * @param getFlags
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.CentralTendencyPeakData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCentralTendencyPeakData", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetCentralTendencyPeakData")
    @ResponseWrapper(localName = "getCentralTendencyPeakDataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetCentralTendencyPeakDataResponse")
    public List<CentralTendencyPeakData> getCentralTendencyPeakData(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "duration", targetNamespace = "")
        Duration duration,
        @WebParam(name = "getFlags", targetNamespace = "")
        boolean getFlags,
        @WebParam(name = "centralTendencyType", targetNamespace = "")
        CentralTendencyType centralTendencyType);

    /**
     * 
     * @param stationTriplets
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.ReservoirMetadata>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReservoirMetadataMultiple", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetReservoirMetadataMultiple")
    @ResponseWrapper(localName = "getReservoirMetadataMultipleResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetReservoirMetadataMultipleResponse")
    public List<ReservoirMetadata> getReservoirMetadataMultiple(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets);

    /**
     * 
     * @param forecastPeriod
     * @param elementCd
     * @param stationTriplet
     * @param publicationDate
     * @return
     *     returns gov.usda.nrcs.wcc.awdbWebService.Forecast
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecast", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecast")
    @ResponseWrapper(localName = "getForecastResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastResponse")
    public Forecast getForecast(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "forecastPeriod", targetNamespace = "")
        String forecastPeriod,
        @WebParam(name = "publicationDate", targetNamespace = "")
        String publicationDate);

    /**
     * 
     * @param stationTriplet
     * @return
     *     returns gov.usda.nrcs.wcc.awdbWebService.ReservoirMetadata
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReservoirMetadata", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetReservoirMetadata")
    @ResponseWrapper(localName = "getReservoirMetadataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetReservoirMetadataResponse")
    public ReservoirMetadata getReservoirMetadata(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet);

    /**
     * 
     * @param beginPublicationDate
     * @param stationTriplet
     * @param endPublicationDate
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.ForecastFull>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllForecastsForStation", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetAllForecastsForStation")
    @ResponseWrapper(localName = "getAllForecastsForStationResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetAllForecastsForStationResponse")
    public List<ForecastFull> getAllForecastsForStation(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet,
        @WebParam(name = "beginPublicationDate", targetNamespace = "")
        String beginPublicationDate,
        @WebParam(name = "endPublicationDate", targetNamespace = "")
        String endPublicationDate);

    /**
     * 
     * @param stationTriplets
     * @param periods
     * @param elementCd
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.ForecastPeriodAverage>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastPeriodAverages", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPeriodAverages")
    @ResponseWrapper(localName = "getForecastPeriodAveragesResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPeriodAveragesResponse")
    public List<ForecastPeriodAverage> getForecastPeriodAverages(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "periods", targetNamespace = "")
        List<String> periods);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @param stationTriplet
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.StationElement>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStationElements", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationElements")
    @ResponseWrapper(localName = "getStationElementsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationElementsResponse")
    public List<StationElement> getStationElements(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet,
        @WebParam(name = "beginDate", targetNamespace = "")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate);

    /**
     * 
     * @param filter
     * @param beginDate
     * @param stationTriplets
     * @param endDate
     * @param heightDepth
     * @param elementCd
     * @param unitSystem
     * @param ordinal
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.InstantaneousData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInstantaneousData", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetInstantaneousData")
    @ResponseWrapper(localName = "getInstantaneousDataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetInstantaneousDataResponse")
    public List<InstantaneousData> getInstantaneousData(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "ordinal", targetNamespace = "")
        int ordinal,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "beginDate", targetNamespace = "")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate,
        @WebParam(name = "filter", targetNamespace = "")
        InstantaneousDataFilter filter,
        @WebParam(name = "unitSystem", targetNamespace = "")
        UnitSystem unitSystem);

    /**
     * 
     * @param duration
     * @param beginDate
     * @param stationTriplets
     * @param endDate
     * @param heightDepth
     * @param elementCd
     * @param getFlags
     * @param alwaysReturnDailyFeb29
     * @param ordinal
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.Data>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetDataResponse")
    public List<Data> getData(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "ordinal", targetNamespace = "")
        int ordinal,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "duration", targetNamespace = "")
        Duration duration,
        @WebParam(name = "getFlags", targetNamespace = "")
        boolean getFlags,
        @WebParam(name = "beginDate", targetNamespace = "")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate,
        @WebParam(name = "alwaysReturnDailyFeb29", targetNamespace = "")
        Boolean alwaysReturnDailyFeb29);

    /**
     * 
     * @param duration
     * @param centralTendencyType
     * @param stationTriplets
     * @param beginDay
     * @param endDay
     * @param heightDepth
     * @param elementCd
     * @param getFlags
     * @param endMonth
     * @param beginMonth
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.CentralTendencyData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCentralTendencyData", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetCentralTendencyData")
    @ResponseWrapper(localName = "getCentralTendencyDataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetCentralTendencyDataResponse")
    public List<CentralTendencyData> getCentralTendencyData(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "duration", targetNamespace = "")
        Duration duration,
        @WebParam(name = "getFlags", targetNamespace = "")
        boolean getFlags,
        @WebParam(name = "beginMonth", targetNamespace = "")
        int beginMonth,
        @WebParam(name = "beginDay", targetNamespace = "")
        int beginDay,
        @WebParam(name = "endMonth", targetNamespace = "")
        int endMonth,
        @WebParam(name = "endDay", targetNamespace = "")
        int endDay,
        @WebParam(name = "centralTendencyType", targetNamespace = "")
        CentralTendencyType centralTendencyType);

    /**
     * 
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.ForecastPeriod>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastPeriods", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPeriods")
    @ResponseWrapper(localName = "getForecastPeriodsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPeriodsResponse")
    public List<ForecastPeriod> getForecastPeriods();

    /**
     * 
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.HeightDepth>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHeightDepths", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetHeightDepths")
    @ResponseWrapper(localName = "getHeightDepthsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetHeightDepthsResponse")
    public List<HeightDepth> getHeightDepths();

    /**
     * 
     * @param stateCds
     * @param stationIds
     * @param logicalAnd
     * @param networkCds
     * @param forecastPointNames
     * @param forecasters
     * @param hucs
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.ForecastPoint>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForecastPoints", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPoints")
    @ResponseWrapper(localName = "getForecastPointsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetForecastPointsResponse")
    public List<ForecastPoint> getForecastPoints(
        @WebParam(name = "stationIds", targetNamespace = "")
        List<String> stationIds,
        @WebParam(name = "stateCds", targetNamespace = "")
        List<String> stateCds,
        @WebParam(name = "networkCds", targetNamespace = "")
        List<String> networkCds,
        @WebParam(name = "forecastPointNames", targetNamespace = "")
        List<String> forecastPointNames,
        @WebParam(name = "hucs", targetNamespace = "")
        List<String> hucs,
        @WebParam(name = "forecasters", targetNamespace = "")
        List<String> forecasters,
        @WebParam(name = "logicalAnd", targetNamespace = "")
        boolean logicalAnd);

    /**
     * 
     * @param stationTriplet
     * @return
     *     returns gov.usda.nrcs.wcc.awdbWebService.StationMetaData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStationMetadata", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationMetadata")
    @ResponseWrapper(localName = "getStationMetadataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetStationMetadataResponse")
    public StationMetaData getStationMetadata(
        @WebParam(name = "stationTriplet", targetNamespace = "")
        String stationTriplet);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "areYouThere", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.AreYouThere")
    @ResponseWrapper(localName = "areYouThereResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.AreYouThereResponse")
    public boolean areYouThere();

    /**
     * 
     * @param duration
     * @param stationTriplets
     * @param heightDepth
     * @param elementCd
     * @param getFlags
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.AveragesPeakData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAveragesPeak", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetAveragesPeak")
    @ResponseWrapper(localName = "getAveragesPeakResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetAveragesPeakResponse")
    public List<AveragesPeakData> getAveragesPeak(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "duration", targetNamespace = "")
        Duration duration,
        @WebParam(name = "getFlags", targetNamespace = "")
        boolean getFlags);

    /**
     * 
     * @param duration
     * @param stationTriplets
     * @param heightDepth
     * @param beginYear
     * @param elementCd
     * @param getFlags
     * @param endYear
     * @param ordinal
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.PeakData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPeakData", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetPeakData")
    @ResponseWrapper(localName = "getPeakDataResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetPeakDataResponse")
    public List<PeakData> getPeakData(
        @WebParam(name = "stationTriplets", targetNamespace = "")
        List<String> stationTriplets,
        @WebParam(name = "elementCd", targetNamespace = "")
        String elementCd,
        @WebParam(name = "ordinal", targetNamespace = "")
        int ordinal,
        @WebParam(name = "heightDepth", targetNamespace = "")
        HeightDepth heightDepth,
        @WebParam(name = "duration", targetNamespace = "")
        Duration duration,
        @WebParam(name = "getFlags", targetNamespace = "")
        boolean getFlags,
        @WebParam(name = "beginYear", targetNamespace = "")
        int beginYear,
        @WebParam(name = "endYear", targetNamespace = "")
        int endYear);

    /**
     * 
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.Unit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUnits", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetUnits")
    @ResponseWrapper(localName = "getUnitsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetUnitsResponse")
    public List<Unit> getUnits();

    /**
     * 
     * @return
     *     returns java.util.List<gov.usda.nrcs.wcc.awdbWebService.Element>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getElements", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetElements")
    @ResponseWrapper(localName = "getElementsResponse", targetNamespace = "http://www.wcc.nrcs.usda.gov/ns/awdbWebService", className = "gov.usda.nrcs.wcc.awdbWebService.GetElementsResponse")
    public List<Element> getElements();

}
